apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitbyte
  labels:
    app.kubernetes.io/name: fitbyte
    app.kubernetes.io/instance: {{ .Release.Name | default "fitbyte" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | default "helm" }}
    helm.sh/chart: fitbyte-0.1.0
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fitbyte
      app.kubernetes.io/instance: {{ .Release.Name | default "fitbyte" }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: fitbyte
        app.kubernetes.io/instance: {{ .Release.Name | default "fitbyte" }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: fitbyte
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range .Values.env }}
            {{- if or (eq .name "DATABASE_URL") (eq .name "SECRET_KEY") (eq .name "JWT_SECRET") }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: fitbyte-secrets
                  key: {{ .name | lower }}
            {{- else }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: fitbyte-config
                  key: {{ .name }}
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}